const discord = require("discord.js") 
const client = new discord.Client()

client.on("ready",() => {
 console.log("I am ready,my mont")
});


client.on("message",message => {
 if (message.content === "!ping"){
   return message.channel.send("Pong" +client.ws.ping)
  }
})

client.login("NzUwNDU4MzYzODYyODQzNDk0.X0600A.EvHvTxpCbUb_Hx3u_uvr6w2NTPQ")